import { DiseaseReport, Cluster, Animal, User } from '../../src/types/index';

// Pre-seeded demo animals for Anand District, Gujarat rural cluster
export const SEED_ANIMALS: Animal[] = [
  {
    id: 'anim-001',
    owner_id: 'farmer-demo-001',
    animal_identifier: 'COW-ANAND-101',
    species: 'Cow',
    breed: 'Gir',
    age: 4,
    sex: 'Female',
    created_at: new Date(Date.now() - 7 * 86400000).toISOString(),
  },
  {
    id: 'anim-002',
    owner_id: 'farmer-demo-001',
    animal_identifier: 'BUF-PETLAD-204',
    species: 'Buffalo',
    breed: 'Murrah',
    age: 5,
    sex: 'Female',
    created_at: new Date(Date.now() - 6 * 86400000).toISOString(),
  },
  {
    id: 'anim-003',
    owner_id: 'farmer-demo-002',
    animal_identifier: 'GOAT-BORSAD-309',
    species: 'Goat',
    breed: 'Surti',
    age: 2,
    sex: 'Male',
    created_at: new Date(Date.now() - 5 * 86400000).toISOString(),
  },
  {
    id: 'anim-004',
    owner_id: 'farmer-demo-003',
    animal_identifier: 'COW-UMRETH-412',
    species: 'Cow',
    breed: 'Kankrej',
    age: 3.5,
    sex: 'Female',
    created_at: new Date(Date.now() - 4 * 86400000).toISOString(),
  },
];

// Pre-seeded high surveillance disease reports around Anand district for instant GIS map visualization
export const SEED_REPORTS: DiseaseReport[] = [
  {
    id: 'rep-anand-801',
    animal_id: 'anim-001',
    animal: SEED_ANIMALS[0],
    reported_by: 'farmer-demo-001',
    reporter_name: 'Ramesh Patel (Anand Village)',
    symptoms: ['fever', 'difficulty_breathing', 'swelling', 'nasal_discharge'],
    affected_count: 6,
    death_count: 2,
    duration_days: 3,
    image_url: 'https://images.unsplash.com/photo-1570042707223-9568778f2444?auto=format&fit=crop&w=600&q=80',
    latitude: 22.5645,
    longitude: 72.9289,
    location_name: 'Anand Milk Cluster Zone A',
    risk_score: 88,
    risk_level: 'CRITICAL',
    contributing_factors: [
      'Mortality reported (2 deaths)',
      '6 animals affected in herd',
      'Severe respiratory distress & edema',
      'High temperature febrile state',
    ],
    status: 'PENDING_VET_REVIEW',
    created_at: new Date(Date.now() - 2 * 3600000).toISOString(),
  },
  {
    id: 'rep-petlad-802',
    animal_id: 'anim-002',
    animal: SEED_ANIMALS[1],
    reported_by: 'farmer-demo-002',
    reporter_name: 'Suresh Parmar (Petlad Sector)',
    symptoms: ['fever', 'swelling', 'loss_of_appetite'],
    affected_count: 4,
    death_count: 1,
    duration_days: 2,
    image_url: 'https://images.unsplash.com/photo-1546445317-29f4545f9d52?auto=format&fit=crop&w=600&q=80',
    latitude: 22.4735,
    longitude: 72.8021,
    location_name: 'Petlad Sub-district Farm 4',
    risk_score: 76,
    risk_level: 'HIGH',
    contributing_factors: [
      'Mortality reported (1 death)',
      'Multiple buffaloes affected',
      'Submandibular swelling observed',
    ],
    status: 'ACCEPTED',
    created_at: new Date(Date.now() - 6 * 3600000).toISOString(),
  },
  {
    id: 'rep-borsad-803',
    animal_id: 'anim-003',
    animal: SEED_ANIMALS[2],
    reported_by: 'farmer-demo-003',
    reporter_name: 'Vikram Solanki (Borsad East)',
    symptoms: ['cough', 'nasal_discharge', 'weakness'],
    affected_count: 3,
    death_count: 0,
    duration_days: 4,
    image_url: 'https://images.unsplash.com/photo-1527153857715-3908f2bae5e8?auto=format&fit=crop&w=600&q=80',
    latitude: 22.4116,
    longitude: 72.8994,
    location_name: 'Borsad Agricultural Belt',
    risk_score: 45,
    risk_level: 'MEDIUM',
    contributing_factors: ['Multiple small ruminants affected', 'Persistent coughing'],
    status: 'FIELD_VISIT',
    created_at: new Date(Date.now() - 12 * 3600000).toISOString(),
  },
  {
    id: 'rep-umreth-804',
    animal_id: 'anim-004',
    animal: SEED_ANIMALS[3],
    reported_by: 'farmer-demo-004',
    reporter_name: 'Mahesh Chaudhari (Umreth Block)',
    symptoms: ['skin_abnormality', 'fever'],
    affected_count: 5,
    death_count: 0,
    duration_days: 5,
    image_url: 'https://images.unsplash.com/photo-1500595046743-cd271d694d30?auto=format&fit=crop&w=600&q=80',
    latitude: 22.6983,
    longitude: 73.1165,
    location_name: 'Umreth Dairy Co-op Region',
    risk_score: 65,
    risk_level: 'HIGH',
    contributing_factors: ['Widespread skin nodules/lesions', 'High fever'],
    status: 'MONITORING',
    created_at: new Date(Date.now() - 18 * 3600000).toISOString(),
  },
  {
    id: 'rep-khambhat-805',
    animal_id: 'anim-001',
    animal: SEED_ANIMALS[0],
    reported_by: 'farmer-demo-005',
    reporter_name: 'Jayesh Vankar (Coastal Belt)',
    symptoms: ['diarrhea', 'weakness'],
    affected_count: 1,
    death_count: 0,
    duration_days: 1,
    image_url: 'https://images.unsplash.com/photo-1545468841-830f6db3a02a?auto=format&fit=crop&w=600&q=80',
    latitude: 22.3149,
    longitude: 72.6192,
    location_name: 'Khambhat Rural Sector 2',
    risk_score: 22,
    risk_level: 'LOW',
    contributing_factors: ['Isolated single animal case', 'Mild gastrointestinal disturbance'],
    status: 'RESOLVED',
    created_at: new Date(Date.now() - 24 * 3600000).toISOString(),
  },
];

// Pre-seeded Spatial Outbreak Clusters
export const SEED_CLUSTERS: Cluster[] = [
  {
    id: 'cluster-anand-001',
    center_latitude: 22.5645,
    center_longitude: 72.9289,
    radius_km: 8.5,
    case_count: 4,
    risk_level: 'CRITICAL',
    status: 'SUSPECTED',
    related_case_ids: ['rep-anand-801', 'rep-petlad-802', 'rep-umreth-804'],
    district_name: 'Anand District North Corridor',
    created_at: new Date(Date.now() - 4 * 3600000).toISOString(),
  },
];
